### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Xenovia22** [dspeedF95/SoA#13]
Hi. For some reason I received this errors:
![Screenshot_3](https://github.com/dspeedF95/SoA/assets/148292241/7421021e-a45a-4e11-b417-8d256c824af8)
![Screenshot_4](https://github.com/dspeedF95/SoA/assets/148292241/930b85ef-4170-4d6c-957c-05740e53df06)

Can you help me?

**Comment by dspeedF95** [comment]
@Xorgroth Have you seen this before?

**Comment by PrEzi3** [comment]
It looks for me to be an authorization error OR -- a misconfiguration of the C drive. 
Normally QSP tries always to get access to the AppData\Roaming where it stores data either permanently (saves) or temporarily (cache).  
A few ideas : 
--Try to run with Admin rights
--where does %appdata% lead to ??   check if the user has full write rights there !!   
--Check if the Variables are set correctly -- especially APPDATA in registry under [HKCU\Volatile Environment]

This is not an issue with this translation -- rather a misconfiguration of a windows machine.

**Comment by DarkSliM13** [comment]
help me
![Безымянный 1](https://github.com/dspeedF95/SoA/assets/148818577/42807b19-a0e7-494e-a69c-6f61c20cb903)

**Comment by PrEzi3** [comment]
> help me !

This is not an HELP-Request thread ! For this use the forums! 
It seems you have a corrupted or not fully downloaded version of the game, where literally a dozen of files are missing.
Redownload THE FULL version of the game.
NOT a problem with the translation and thus has nothing to do with this thread, plus --- on github IF you have a new issue, you open a new ticket and not post in the current one....  @dspeedF95    I think we can close this whole issue as this is clearly not an issue with the translation... (in both cases).
